// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtkbDxVtTbw3yafrkwHu6XEwOT1-_oHFs',
    appId: '1:885619811485:web:abbb3e351d4dc281a8e074',
    messagingSenderId: '885619811485',
    projectId: 'english-teacher-helper-9693a',
    authDomain: 'english-teacher-helper-9693a.firebaseapp.com',
    storageBucket: 'english-teacher-helper-9693a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTgHsde9EkDQkitaEHFaV8n1EJg7n2vrU',
    appId: '1:885619811485:android:a75275cef02a072ba8e074',
    messagingSenderId: '885619811485',
    projectId: 'english-teacher-helper-9693a',
    storageBucket: 'english-teacher-helper-9693a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOYZIsSmXe0_YWXbZSNNWOLGigCDOcI0',
    appId: '1:885619811485:ios:ffef4f8c4c3f3657a8e074',
    messagingSenderId: '885619811485',
    projectId: 'english-teacher-helper-9693a',
    storageBucket: 'english-teacher-helper-9693a.firebasestorage.app',
    iosBundleId: 'com.example.englishTeachersHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOYZIsSmXe0_YWXbZSNNWOLGigCDOcI0',
    appId: '1:885619811485:ios:ffef4f8c4c3f3657a8e074',
    messagingSenderId: '885619811485',
    projectId: 'english-teacher-helper-9693a',
    storageBucket: 'english-teacher-helper-9693a.firebasestorage.app',
    iosBundleId: 'com.example.englishTeachersHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtkbDxVtTbw3yafrkwHu6XEwOT1-_oHFs',
    appId: '1:885619811485:web:e368accedf89f6e4a8e074',
    messagingSenderId: '885619811485',
    projectId: 'english-teacher-helper-9693a',
    authDomain: 'english-teacher-helper-9693a.firebaseapp.com',
    storageBucket: 'english-teacher-helper-9693a.firebasestorage.app',
  );

}